import type {
  GetStaticPathsContext,
  GetStaticPropsContext,
  InferGetStaticPropsType,
} from 'next'
import { useRouter } from 'next/router'
import commerce from '@lib/api/commerce'
import { Layout } from '@components/common'
import { ProductView } from '@components/product'
import { ProductProvider } from '@components/product/productProvider'
export async function getStaticProps({
  params,
  locale,
  locales,
  preview,
}: GetStaticPropsContext<{ slug: string }>) {
  const config = { locale, locales }
  const pagesPromise = commerce.getAllPages({ config, preview })
  const siteInfoPromise = commerce.getSiteInfo({ config, preview })
  const productPromise = commerce.getProduct({
    variables: { slug: params!.slug },
    config,
    preview,
  })

  const allProductsPromise = commerce.getAllProducts({
    //variables: { first: 4 },
    config,
    preview,
  })

  const { pages } = await pagesPromise
  const { categories } = await siteInfoPromise
  const { product } = await productPromise
  const { products: allProducts } = await allProductsPromise

  if (!product) {
    throw new Error(`Product with slug '${params!.slug}' not found`)
  }
  console.log(product)

  return {
    props: {
      pages,
      product,
      allProducts,
      categories,
    },
    revalidate: 20,
  }
}

export async function getStaticPaths({ locales }: GetStaticPathsContext) {
  const { products } = await commerce.getAllProductPaths()

  return {
    paths: locales
      ? locales.reduce<string[]>((arr, locale) => {
          // Add a product path for every locale
          products.forEach((product: any) => {
            arr.push(`/${locale}/product${product.path}`)
          })
          return arr
        }, [])
      : products.map((product: any) => `/product${product.path}`),
    fallback: 'blocking',
    //fallback can be set as true, false or blocking. when false, if one page was not in pages when initially generated all the
    //pages in getstaticpaths, it will be redirected to 404. when true, for the same context, you can make it return a dummy page
    // by checing if router.fallback ===true  like returning loading or others until getstaticprops and getstaticpaths
    //regenerating this new page. when blocking, there will be no dummy page return like loading, it will just wait for
    //the new page generated by getstaticparops.
  }
}

export default function Slug({
  product,
  allProducts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const router = useRouter()

  return router.isFallback ? (
    <h1>Loading...</h1>
  ) : (
    <ProductProvider product={product} allProducts={allProducts}>
      <ProductView />
    </ProductProvider>
  )
}

Slug.Layout = Layout
